## В этом домашнем задании вы сделаете первые шаги в мире линейной бинарной классификации!

In [1]:
import pandas as pd
import numpy as np
import warnings

#### Задание 1

Мы будем работать с данными **Microsoft Malware Detection**

Таргетом будет последний столбец `HasDetection`, который принимает значения $\{0,\, 1\}$ в случае отсутствия или наличия вируса на компьютере соответственно. Признаками будут выступать всевозможные характеристики компьютера.

In [3]:
data = pd.read_csv('train.csv', low_memory=False)

In [4]:
data.head()

,MachineIdentifier,ProductName,EngineVersion,AppVersion,AvSigVersion,IsBeta,RtpStateBitfield,IsSxsPassiveMode,DefaultBrowsersIdentifier,AVProductStatesIdentifier,...,Census_FirmwareVersionIdentifier,Census_IsSecureBootEnabled,Census_IsWIMBootEnabled,Census_IsVirtualDevice,Census_IsTouchEnabled,Census_IsPenCapable,Census_IsAlwaysOnAlwaysConnectedCapable,Wdft_IsGamer,Wdft_RegionIdentifier,HasDetections
0,0000028988387b115f69f31a3bf04f09,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1735.0,0,7.0,0,NaN,53447.0,...,36144.0,0,NaN,0.0,0,0,0.0,0.0,10.0,0
1,000007535c3f730efa9ea0b7ef1bd645,win8defender,1.1.14600.4,4.13.17134.1,1.263.48.0,0,7.0,0,NaN,53447.0,...,57858.0,0,NaN,0.0,0,0,0.0,0.0,8.0,0
2,000007905a28d863f6d0d597892cd692,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1341.0,0,7.0,0,NaN,53447.0,...,52682.0,0,NaN,0.0,0,0,0.0,0.0,3.0,0
3,00000b11598a75ea8ba1beea8459149f,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1527.0,0,7.0,0,NaN,53447.0,...,20050.0,0,NaN,0.0,0,0,0.0,0.0,3.0,1
4,000014a5f00daa18e76b81417eeb99fc,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1379.0,0,7.0,0,NaN,53447.0,...,19844.0,0,0.0,0.0,0,0,0.0,0.0,1.0,1

In [5]:
data[['ProductName', 'MachineIdentifier']]

         ProductName                 MachineIdentifier
0       win8defender  0000028988387b115f69f31a3bf04f09
1       win8defender  000007535c3f730efa9ea0b7ef1bd645
2       win8defender  000007905a28d863f6d0d597892cd692
3       win8defender  00000b11598a75ea8ba1beea8459149f
4       win8defender  000014a5f00daa18e76b81417eeb99fc
...              ...                               ...
199995  win8defender  05c15aa6487f9710169e37c749a10441
199996  win8defender  05c15b7b1b0f9f19a3279eee6572b3cd
199997  win8defender  05c15e17f59c0e298c06dea9ed3a3ab4
199998  win8defender  05c15e1affb2558420062f2d994f90d1
199999  win8defender  05c15f9f4d9c60d9f4e60033095d4792

[200000 rows x 2 columns]

In [6]:
data.columns

Index(['MachineIdentifier', 'ProductName', 'EngineVersion', 'AppVersion',
       'AvSigVersion', 'IsBeta', 'RtpStateBitfield', 'IsSxsPassiveMode',
       'DefaultBrowsersIdentifier', 'AVProductStatesIdentifier',
       'AVProductsInstalled', 'AVProductsEnabled', 'HasTpm',
       'CountryIdentifier', 'CityIdentifier', 'OrganizationIdentifier',
       'GeoNameIdentifier', 'LocaleEnglishNameIdentifier', 'Platform',
       'Processor', 'OsVer', 'OsBuild', 'OsSuite', 'OsPlatformSubRelease',
       'OsBuildLab', 'SkuEdition', 'IsProtected', 'AutoSampleOptIn', 'PuaMode',
       'SMode', 'IeVerIdentifier', 'SmartScreen', 'Firewall', 'UacLuaenable',
       'Census_MDC2FormFactor', 'Census_DeviceFamily',
       'Census_OEMNameIdentifier', 'Census_OEMModelIdentifier',
       'Census_ProcessorCoreCount', 'Census_ProcessorManufacturerIdentifier',
       'Census_ProcessorModelIdentifier', 'Census_ProcessorClass',
       'Census_PrimaryDiskTotalCapacity', 'Census_PrimaryDiskTypeName',
       'Census_SystemVolumeTotalCapacity', 'Census_HasOpticalDiskDrive',
       'Census_TotalPhysicalRAM', 'Census_ChassisTypeName',
       'Census_InternalPrimaryDiagonalDisplaySizeInInches',
       'Census_InternalPrimaryDisplayResolutionHorizontal',
       'Census_InternalPrimaryDisplayResolutionVertical',
       'Census_PowerPlatformRoleName', 'Census_InternalBatteryType',
       'Census_InternalBatteryNumberOfCharges', 'Census_OSVersion',
       'Census_OSArchitecture', 'Census_OSBranch', 'Census_OSBuildNumber',
       'Census_OSBuildRevision', 'Census_OSEdition', 'Census_OSSkuName',
       'Census_OSInstallTypeName', 'Census_OSInstallLanguageIdentifier',
       'Census_OSUILocaleIdentifier', 'Census_OSWUAutoUpdateOptionsName',
       'Census_IsPortableOperatingSystem', 'Census_GenuineStateName',
       'Census_ActivationChannel', 'Census_IsFlightingInternal',
       'Census_IsFlightsDisabled', 'Census_FlightRing',
       'Census_ThresholdOptIn', 'Census_FirmwareManufacturerIdentifier',
       'Census_FirmwareVersionIdentifier', 'Census_IsSecureBootEnabled',
       'Census_IsWIMBootEnabled', 'Census_IsVirtualDevice',
       'Census_IsTouchEnabled', 'Census_IsPenCapable',
       'Census_IsAlwaysOnAlwaysConnectedCapable', 'Wdft_IsGamer',
       'Wdft_RegionIdentifier', 'HasDetections'],
      dtype='object')

Удалите константные признаки и признаки `ProductName` `MachineIdentifier`

In [7]:
constant_features = []
numeric_columns = data.loc[:,data.dtypes!=object].columns
for col in numeric_columns:
    if np.max(data[col]) == np.min(data[col]):
        constant_features.append(col)

print(constant_features)

['IsBeta', 'Census_IsWIMBootEnabled']

In [8]:
### Your code is here
data = data.drop(['ProductName', 'MachineIdentifier','IsBeta', 'Census_IsWIMBootEnabled'], axis=1)

Посмотрите на соотношение классов в таргете. Все ли хорошо?

In [9]:
print(sum(data['HasDetections'] == 1), '- positive class,')
print(sum(data['HasDetections'] == 0), '- negative class')

100060 - positive class,
99940 - negative class

Ответьте на вопрос: почему с вашей точки зрения важно иметь представление о балансе классов в ваших данных?

Избавьтесь от пропусков в данных! 

Новый для нас прием: признаки с более чем половиной пропусков следует удалить.

Согласитесь, если в вашей колонке среди 100 объектов всего лишь у 2 есть какое-то непропущенное значение, странно все остальные заполнять средним от этих двух чисел. Такие "редкие" признаки лучше вообще опустить!


В категориальных колонках заменим отсутствующую категорию просто некоторой новой и назовем ее `NaN`.

А в числовых, ради разнообразия, заполним пропуски медианным значением.

In [10]:
half_lenght = len(data) / 2
half_lenght

100000.0

In [11]:
more_half=[]
for col in data.columns:
    if data[col].isna().sum() >= half_lenght:
        more_half.append(col)
more_half

['DefaultBrowsersIdentifier',
 'PuaMode',
 'Census_ProcessorClass',
 'Census_InternalBatteryType',
 'Census_IsFlightingInternal',
 'Census_ThresholdOptIn']

In [12]:
data = data.drop(more_half, axis=1)
data.shape

(200000, 73)

In [13]:
### Your code is here
list_nan=[]
for col in data.columns:
    if data[col].isna().sum()>0:
        list_nan.append(col)
        print(f" в колонке {col} {data[col].isna().sum()} пропусков , тип {data[col].dtypes}")

 в колонке RtpStateBitfield 764 пропусков , тип float64
 в колонке AVProductStatesIdentifier 804 пропусков , тип float64
 в колонке AVProductsInstalled 804 пропусков , тип float64
 в колонке AVProductsEnabled 804 пропусков , тип float64
 в колонке CityIdentifier 7215 пропусков , тип float64
 в колонке OrganizationIdentifier 61537 пропусков , тип float64
 в колонке GeoNameIdentifier 1 пропусков , тип float64
 в колонке OsBuildLab 1 пропусков , тип object
 в колонке IsProtected 799 пропусков , тип float64
 в колонке SMode 11863 пропусков , тип float64
 в колонке IeVerIdentifier 1362 пропусков , тип float64
 в колонке SmartScreen 71123 пропусков , тип object
 в колонке Firewall 2078 пропусков , тип float64
 в колонке UacLuaenable 248 пропусков , тип float64
 в колонке Census_OEMNameIdentifier 2082 пропусков , тип float64
 в колонке Census_OEMModelIdentifier 2245 пропусков , тип float64
 в колонке Census_ProcessorCoreCount 922 пропусков , тип float64
 в колонке Census_ProcessorManufacturerIdentifier 922 пропусков , тип float64
 в колонке Census_ProcessorModelIdentifier 923 пропусков , тип float64
 в колонке Census_PrimaryDiskTotalCapacity 1173 пропусков , тип float64
 в колонке Census_PrimaryDiskTypeName 292 пропусков , тип object
 в колонке Census_SystemVolumeTotalCapacity 1173 пропусков , тип float64
 в колонке Census_TotalPhysicalRAM 1822 пропусков , тип float64
 в колонке Census_ChassisTypeName 9 пропусков , тип object
 в колонке Census_InternalPrimaryDiagonalDisplaySizeInInches 1111 пропусков , тип float64
 в колонке Census_InternalPrimaryDisplayResolutionHorizontal 1109 пропусков , тип float64
 в колонке Census_InternalPrimaryDisplayResolutionVertical 1109 пропусков , тип float64
 в колонке Census_InternalBatteryNumberOfCharges 6065 пропусков , тип float64
 в колонке Census_OSInstallLanguageIdentifier 1331 пропусков , тип float64
 в колонке Census_IsFlightsDisabled 3541 пропусков , тип float64
 в колонке Census_FirmwareManufacturerIdentifier 4101 пропусков , тип float64
 в колонке Census_FirmwareVersionIdentifier 3586 пропусков , тип float64
 в колонке Census_IsVirtualDevice 348 пропусков , тип float64
 в колонке Census_IsAlwaysOnAlwaysConnectedCapable 1621 пропусков , тип float64
 в колонке Wdft_IsGamer 6737 пропусков , тип float64
 в колонке Wdft_RegionIdentifier 6737 пропусков , тип float64

In [14]:
numeric_columns = data.loc[:,data.dtypes!=object].columns
for col in numeric_columns:
    data[col]=data[col].fillna(data[col].median())
print(data[numeric_columns].isna().sum())

RtpStateBitfield                                     0
IsSxsPassiveMode                                     0
AVProductStatesIdentifier                            0
AVProductsInstalled                                  0
AVProductsEnabled                                    0
HasTpm                                               0
CountryIdentifier                                    0
CityIdentifier                                       0
OrganizationIdentifier                               0
GeoNameIdentifier                                    0
LocaleEnglishNameIdentifier                          0
OsBuild                                              0
OsSuite                                              0
IsProtected                                          0
AutoSampleOptIn                                      0
SMode                                                0
IeVerIdentifier                                      0
Firewall                                             0
UacLuaenable                                         0
Census_OEMNameIdentifier                             0
Census_OEMModelIdentifier                            0
Census_ProcessorCoreCount                            0
Census_ProcessorManufacturerIdentifier               0
Census_ProcessorModelIdentifier                      0
Census_PrimaryDiskTotalCapacity                      0
Census_SystemVolumeTotalCapacity                     0
Census_HasOpticalDiskDrive                           0
Census_TotalPhysicalRAM                              0
Census_InternalPrimaryDiagonalDisplaySizeInInches    0
Census_InternalPrimaryDisplayResolutionHorizontal    0
Census_InternalPrimaryDisplayResolutionVertical      0
Census_InternalBatteryNumberOfCharges                0
Census_OSBuildNumber                                 0
Census_OSBuildRevision                               0
Census_OSInstallLanguageIdentifier                   0
Census_OSUILocaleIdentifier                          0
Census_IsPortableOperatingSystem                     0
Census_IsFlightsDisabled                             0
Census_FirmwareManufacturerIdentifier                0
Census_FirmwareVersionIdentifier                     0
Census_IsSecureBootEnabled                           0
Census_IsVirtualDevice                               0
Census_IsTouchEnabled                                0
Census_IsPenCapable                                  0
Census_IsAlwaysOnAlwaysConnectedCapable              0
Wdft_IsGamer                                         0
Wdft_RegionIdentifier                                0
HasDetections                                        0
dtype: int64

In [15]:
### 1 ВАРИАНТ КАК ОПРЕДЕЛИТЬ КАТЕГОРИАЛЬНЫЕ КОЛОНКИ

categorical_columns = data.select_dtypes(include=['object', 'category']).columns
data[categorical_columns]
for col in categorical_columns:
    data[col]=data[col].fillna('NaN')
print(data[categorical_columns].isna().sum())

EngineVersion                       0
AppVersion                          0
AvSigVersion                        0
Platform                            0
Processor                           0
OsVer                               0
OsPlatformSubRelease                0
OsBuildLab                          0
SkuEdition                          0
SmartScreen                         0
Census_MDC2FormFactor               0
Census_DeviceFamily                 0
Census_PrimaryDiskTypeName          0
Census_ChassisTypeName              0
Census_PowerPlatformRoleName        0
Census_OSVersion                    0
Census_OSArchitecture               0
Census_OSBranch                     0
Census_OSEdition                    0
Census_OSSkuName                    0
Census_OSInstallTypeName            0
Census_OSWUAutoUpdateOptionsName    0
Census_GenuineStateName             0
Census_ActivationChannel            0
Census_FlightRing                   0
dtype: int64

In [16]:
### 2 ВАРИАНТ КАК ОПРЕДЕЛИТЬ КАТЕГОРИАЛЬНЫЕ КОЛОНКИ
categorical_columns = data.loc[:,data.dtypes==object].columns
for col in categorical_columns:
    data[col]=data[col].fillna('NaN')
print(data[categorical_columns].isna().sum())

EngineVersion                       0
AppVersion                          0
AvSigVersion                        0
Platform                            0
Processor                           0
OsVer                               0
OsPlatformSubRelease                0
OsBuildLab                          0
SkuEdition                          0
SmartScreen                         0
Census_MDC2FormFactor               0
Census_DeviceFamily                 0
Census_PrimaryDiskTypeName          0
Census_ChassisTypeName              0
Census_PowerPlatformRoleName        0
Census_OSVersion                    0
Census_OSArchitecture               0
Census_OSBranch                     0
Census_OSEdition                    0
Census_OSSkuName                    0
Census_OSInstallTypeName            0
Census_OSWUAutoUpdateOptionsName    0
Census_GenuineStateName             0
Census_ActivationChannel            0
Census_FlightRing                   0
dtype: int64

Создайте копию полученного датафрейма и положите ее в переменную data_2. Понадобится в следующих заданиях.

In [17]:
data.isna().sum().sum()

0

In [18]:
data_2 = data.copy()
data_2.shape[1]

73

Так же поработаем над всеми категориальными колонкам перед запуском непосредственно моделей.

Провернем самый базовый и наглый метод - несмотря на количество уникальных значений в каждой категории, просто применим ко всей категориальной части датасета `OneHotEncoding`

In [19]:
### Your code is here
for col in categorical_columns :
    one_hot=pd.get_dummies(data[col], prefix=col, drop_first=True)
    data = pd.concat((data.drop(col, axis=1), one_hot), axis=1)
print(len(data.columns))
print(data.shape[1])

6114
6114

###  Разделим выборку на тренировочную и тестовую

P.S. в задачах классификации, как и в задаче регрессии, можно использовать технологию Кросс-Валидации. Например, по одному из двух следующих сценариев:

1) Отделить валидацию и тест, произвести подбор лучшей модели с помощью `K-Fold` на валидации, финально обучить выбранную модель на всей валидации и замерить качество на заранее отложенном финальном тесте!

2) Всю выборку назвать валидационной и на ней применить `K-Fold` без финального замера.

В этой домашней работе попросим Вас быть еще проще! :)
Реализуем просто технологию отложенной выборки в пропорции 3:1

In [20]:
from sklearn.model_selection import train_test_split 

X = data.drop(columns=['HasDetections'])
y = data['HasDetections']

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.25,
                                                    shuffle=True,
                                                    random_state=1)

Соберите `Pipeline`, реализовав в нем 2 шага: стандартизация данных через `StandardScaler` и обучение логистической регрессии с помощью `LogisticRegression`, положите результаты в переменную `pipe`, а в классе модели `LogisticRegression` укажите параметр `penalty='none'`

In [21]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

### Your code is here

pipe = Pipeline([('scaler', StandardScaler()),
                 ('LR', LogisticRegression(penalty=None))])

pipe.fit(X_train, y_train)
pipe.score(X_test, y_test)

0.62246

Чтобы замерить качество работы такой модели на трейне и на тесте воспользуемся функцией `cross_validate`

Вопрос: что передавать ей в параметр cv? Ведь мы уже разделили нашу выборку на трейн и тест (имеем всего 1 fold). Для этого можно просто передать список от кортежа, содержащего индексы тренировочных и тестовых объектов.

In [22]:
from sklearn.model_selection import cross_validate
import datetime

custom_cv = [(X_train.index.to_list(), X_test.index.to_list())]

begin_time = datetime.datetime.now()

cv_result_pipe = cross_validate(pipe, X, y, scoring='accuracy',
                                cv=custom_cv, return_train_score=True)


print(f"Accuracy на трейне: {np.mean(cv_result_pipe['train_score']).round(3)}")
print(f"Accuracy на тесте: {np.mean(cv_result_pipe['test_score']).round(3)}")

print(f"Время работы алгоритма: {datetime.datetime.now() - begin_time}")

Accuracy на трейне: 0.651
Accuracy на тесте: 0.622
Время работы алгоритма: 0:02:27.082216

Что можете сказать про время работы алгоритма?

Очевидно, оно достаточно большие. Уж тем более для линейных моделей.

Такое как раз-таки происходит из-за того, что количество фичей, который мы передали нашей модели - гигантское! Классу требуется много времени и памяти, чтобы обработать датасет.

Поэтому те колонки, в которых количество уникальных категорий превышает какое-то адекватное число, следует кодировать иначе, нежели с помощью технологии `One-Hot-Encoding`.

Теперь вы верите, что более умные кодировки зачастую прям необходимы! Раньше мы этот факт не демонстрировали!

Дело еще вот в чем: в классе `LogisticRegression`, как и, например, `Lasso`, есть параметр, ограничивающий максимальное количество итераций во время обучения модели. Так, если данных много и итераций тоже ожидается большое число, найденная разделяющая гиперплоскость может оказаться не самой лучшей, так как наш алгоритм (будь то градиентный спуск или любой иной) просто 'не доползет'.

#### Задание 2

Теперь попробуем другой метод кодирования категориальных колонок, а именно счётчики.
Построем ту же модель и на том же разделении, просто заново иначе переобработаем датасет. 

Для тех категориальных признаков, у которых количество уникальных значений в колоночках больше 5, применим `MeanTargetEncoding`.

Для остальных оставим любимый `OneHotEncoding` (как делали на практике и в предыдущем уроке).

In [23]:
### Your code is here
data_2.shape[1]
for col in categorical_columns :
    if data_2[col].nunique() <= 5:
        one_hot=pd.get_dummies(data_2[col], prefix=col, drop_first=True)
        data_2 = pd.concat((data_2.drop(col, axis=1), one_hot), axis=1)
    else:
        mean_target = data_2.groupby(col)['HasDetections'].mean()
        data_2[col] = data_2[col].map(mean_target)
        
print(len(data_2.columns))
print(data_2.shape[1])

82
82

In [24]:
X_2 = data_2.drop(columns=['HasDetections'])
y_2 = data_2['HasDetections']

Опять обучим модель, пока что без изменений! Скажите, стало ли быстрее? А что с качеством?

In [25]:
### Your code is here


custom_cv = [(X_train.index.to_list(), X_test.index.to_list())]

begin_time = datetime.datetime.now()

cv_result_pipe = cross_validate(pipe, X_2, y_2, scoring='accuracy',
                                cv=custom_cv, return_train_score=True)


print(f"Accuracy на трейне: {np.mean(cv_result_pipe['train_score']).round(3)}")
print(f"Accuracy на тесте: {np.mean(cv_result_pipe['test_score']).round(3)}")

print(f"Время работы алгоритма: {datetime.datetime.now() - begin_time}")

Accuracy на трейне: 0.638
Accuracy на тесте: 0.638
Время работы алгоритма: 0:00:01.778222

#### Задание 3: Регуляризация

Как и в моделях регрессии, решая задачу классификации, можем штрафовать минимизируемый функционал за большие веса, добавив к нему L1 или L2 норму весов (все как раньше!).

Для этого в изначальном классе `LogisticRegression` изменить параметр `penalty` на l1 или l2 соответственно. Выберите второй вариант! Можно воспользоваться методом `set_params` и применить его к `pipe`.

In [26]:
### Your code is here
X_train, X_test, y_train, y_test = train_test_split(X_2, y_2,
                                                    test_size=0.25,
                                                    shuffle=True,
                                                    random_state=1)
custom_cv = [(X_train.index.to_list(), X_test.index.to_list())]

pipe = Pipeline([('scaler', StandardScaler()),
                 ('LR', LogisticRegression(penalty='l2'))])

pipe.fit(X_train, y_train)
pipe.score(X_test, y_test)


begin_time = datetime.datetime.now()

cv_result_pipe = cross_validate(pipe, X_2, y_2, scoring='accuracy',
                                cv=custom_cv, return_train_score=True)


print(f"Accuracy на трейне: {np.mean(cv_result_pipe['train_score']).round(3)}")
print(f"Accuracy на тесте: {np.mean(cv_result_pipe['test_score']).round(3)}")

print(f"Время работы алгоритма: {datetime.datetime.now() - begin_time}")

Accuracy на трейне: 0.638
Accuracy на тесте: 0.638
Время работы алгоритма: 0:00:01.654706

Теперь наша модель будет строить логистическую регрессию с L2 регуляризатором! Помним, что у регуляризируемых моделей есть гиперпараметр, контролирующий силу регуляризации, который выбирается ДО запуска метода fit, то есть заранее, когда модель еще не обучена. 

Конечно же, выбор этого параметра влияет итоговые результаты. Хочется поперебирать различные параметры регуляризации и найти такой, при котором качество на тесте окажется лучшим! 

Сгенерируем массив гиперпараметра, которые планируем перебрать:

In [27]:
alphas = np.linspace(0.0001, 0.01, 100)
alphas

array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009, 0.001 , 0.0011, 0.0012, 0.0013, 0.0014, 0.0015, 0.0016,
       0.0017, 0.0018, 0.0019, 0.002 , 0.0021, 0.0022, 0.0023, 0.0024,
       0.0025, 0.0026, 0.0027, 0.0028, 0.0029, 0.003 , 0.0031, 0.0032,
       0.0033, 0.0034, 0.0035, 0.0036, 0.0037, 0.0038, 0.0039, 0.004 ,
       0.0041, 0.0042, 0.0043, 0.0044, 0.0045, 0.0046, 0.0047, 0.0048,
       0.0049, 0.005 , 0.0051, 0.0052, 0.0053, 0.0054, 0.0055, 0.0056,
       0.0057, 0.0058, 0.0059, 0.006 , 0.0061, 0.0062, 0.0063, 0.0064,
       0.0065, 0.0066, 0.0067, 0.0068, 0.0069, 0.007 , 0.0071, 0.0072,
       0.0073, 0.0074, 0.0075, 0.0076, 0.0077, 0.0078, 0.0079, 0.008 ,
       0.0081, 0.0082, 0.0083, 0.0084, 0.0085, 0.0086, 0.0087, 0.0088,
       0.0089, 0.009 , 0.0091, 0.0092, 0.0093, 0.0094, 0.0095, 0.0096,
       0.0097, 0.0098, 0.0099, 0.01  ])

Чтобы отобрать среди данного массива гиперпараметров лучший, воспользуйтесь конструкцией `GridSearchCV` из `sklearn`

In [28]:
from sklearn.model_selection import GridSearchCV

param_grid ={
    'LR__C': alphas
}

### Your code is here
search = GridSearchCV(pipe, param_grid, cv=custom_cv, scoring='accuracy')
search.fit(X_2, y_2)


print(f"Best parameter (CV score={search.best_score_:.5f}):")
print(search.best_params_)

Best parameter (CV score=0.63842):
{'LR__C': 0.0006000000000000001}

In [29]:
search.cv_results_

{'mean_fit_time': array([0.81945157, 0.86249566, 0.8845315 , 0.94294834, 0.93801951,
        0.9385426 , 0.93298244, 0.94467187, 0.94829798, 0.98749781,
        0.92367578, 0.97030234, 0.99121928, 0.98425937, 1.05007744,
        1.01558971, 1.04132915, 1.03353953, 1.00476813, 1.0113287 ,
        1.02012277, 1.0264647 , 0.99971104, 1.01366901, 1.08970976,
        1.18778706, 1.04495955, 1.06731033, 1.06578612, 1.01611757,
        1.02012372, 0.99114347, 0.98929214, 0.9870863 , 1.00332379,
        1.01522541, 1.00015807, 1.00972056, 1.00027823, 1.02538776,
        1.00050592, 1.01620388, 1.01329136, 0.98466825, 1.01485133,
        1.00110269, 0.98452902, 1.01085162, 0.98711514, 1.00279784,
        1.07534266, 1.13107085, 0.98239779, 1.16900468, 0.99826336,
        1.12527871, 1.05759358, 1.09280109, 1.00361872, 0.99951315,
        1.03453207, 0.99953508, 1.07065058, 1.05527139, 0.99515462,
        1.04008698, 1.06530499, 1.04875803, 1.01083636, 0.97494578,
        0.98478985, 1.00564265, 0.96202803, 1.00007987, 0.99970508,
        1.01341486, 0.99934411, 1.0018611 , 1.00878143, 0.9931953 ,
        1.02039814, 1.01829553, 1.00229383, 0.99719405, 1.01448631,
        1.04875922, 1.11083913, 1.11174536, 1.03118563, 1.00215936,
        1.01715255, 1.00291967, 1.05391622, 1.02683282, 1.00369   ,
        1.0023756 , 0.98446846, 1.08547401, 1.15615177, 1.25518441]),
 'std_fit_time': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'mean_score_time': array([0.1252861 , 0.12232757, 0.11083221, 0.12483525, 0.12759495,
        0.12847066, 0.1187191 , 0.12282133, 0.12906098, 0.15845132,
        0.1553669 , 0.12456369, 0.11888838, 0.12526488, 0.12239337,
        0.12977695, 0.15768647, 0.1228106 , 0.11975956, 0.11441255,
        0.12027669, 0.12397599, 0.12541461, 0.14023209, 0.1325748 ,
        0.12408757, 0.12551141, 0.13495159, 0.13277078, 0.12454128,
        0.11693597, 0.10360765, 0.12562466, 0.106987  , 0.14435148,
        0.10978341, 0.12602639, 0.10175943, 0.1245544 , 0.11394835,
        0.12346125, 0.1283443 , 0.1185813 , 0.12539768, 0.1088717 ,
        0.11486936, 0.12519622, 0.11238289, 0.13851237, 0.11371541,
        0.13542533, 0.1189723 , 0.10774469, 0.13432455, 0.10728836,
        0.1088531 , 0.11387897, 0.10935068, 0.10988855, 0.1412394 ,
        0.10990858, 0.11090517, 0.14318848, 0.11640835, 0.10414338,
        0.12555718, 0.11264539, 0.11022019, 0.10935116, 0.12871599,
        0.1231482 , 0.13613749, 0.13561845, 0.10927653, 0.13197231,
        0.10838246, 0.12473226, 0.1234622 , 0.11283779, 0.13720202,
        0.11385107, 0.10727382, 0.10624933, 0.11994386, 0.11080289,
        0.12200499, 0.12392902, 0.11960077, 0.10994172, 0.10273886,
        0.11205745, 0.14440799, 0.12943745, 0.10463929, 0.10529327,
        0.11296439, 0.12052488, 0.10904312, 0.12152529, 0.11694217]),
 'std_score_time': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'param_LR__C': masked_array(data=[0.0001, 0.0002, 0.00030000000000000003, 0.0004, 0.0005,
                    0.0006000000000000001, 0.0007000000000000001, 0.0008,
                    0.0009000000000000001, 0.001, 0.0011,
                    0.0012000000000000001, 0.0013000000000000002,
                    0.0014000000000000002, 0.0015, 0.0016,
                    0.0017000000000000001, 0.0018000000000000002,
                    0.0019000000000000002, 0.002, 0.0021, 0.0022, 0.0023,
                    0.0024, 0.0025, 0.0026, 0.0027, 0.0028, 0.0029, 0.003,
                    0.0031, 0.0032, 0.0033, 0.0034, 0.0035, 0.0036, 0.0037,
                    0.0038, 0.0039, 0.004, 0.0041, 0.004200000000000001,
                    0.004300000000000001, 0.0044, 0.0045000000000000005,
                    0.004600000000000001, 0.0047, 0.0048000000000000004,
                    0.004900000000000001, 0.005, 0.0051,
                    0.005200000000000001, 0.005300000000000001, 0.0054,
                    0.0055000000000000005, 0.005600000000000001, 0.0057,
                    0.0058000000000000005, 0.005900000000000001, 0.006,
                    0.0061, 0.006200000000000001, 0.006300000000000001,
                    0.0064, 0.006500000000000001, 0.006600000000000001,
                    0.0067, 0.0068000000000000005, 0.006900000000000001,
                    0.007000000000000001, 0.0071, 0.007200000000000001,
                    0.007300000000000001, 0.0074, 0.007500000000000001,
                    0.007600000000000001, 0.0077, 0.0078000000000000005,
                    0.0079, 0.008, 0.0081, 0.008199999999999999, 0.0083,
                    0.0084, 0.0085, 0.0086, 0.0087, 0.0088, 0.0089, 0.009,
                    0.0091, 0.0092, 0.0093, 0.0094, 0.0095, 0.0096, 0.0097,
                    0.0098, 0.009899999999999999, 0.01],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=1e+20),
 'params': [{'LR__C': 0.0001},
  {'LR__C': 0.0002},
  {'LR__C': 0.00030000000000000003},
  {'LR__C': 0.0004},
  {'LR__C': 0.0005},
  {'LR__C': 0.0006000000000000001},
  {'LR__C': 0.0007000000000000001},
  {'LR__C': 0.0008},
  {'LR__C': 0.0009000000000000001},
  {'LR__C': 0.001},
  {'LR__C': 0.0011},
  {'LR__C': 0.0012000000000000001},
  {'LR__C': 0.0013000000000000002},
  {'LR__C': 0.0014000000000000002},
  {'LR__C': 0.0015},
  {'LR__C': 0.0016},
  {'LR__C': 0.0017000000000000001},
  {'LR__C': 0.0018000000000000002},
  {'LR__C': 0.0019000000000000002},
  {'LR__C': 0.002},
  {'LR__C': 0.0021},
  {'LR__C': 0.0022},
  {'LR__C': 0.0023},
  {'LR__C': 0.0024},
  {'LR__C': 0.0025},
  {'LR__C': 0.0026},
  {'LR__C': 0.0027},
  {'LR__C': 0.0028},
  {'LR__C': 0.0029},
  {'LR__C': 0.003},
  {'LR__C': 0.0031},
  {'LR__C': 0.0032},
  {'LR__C': 0.0033},
  {'LR__C': 0.0034},
  {'LR__C': 0.0035},
  {'LR__C': 0.0036},
  {'LR__C': 0.0037},
  {'LR__C': 0.0038},
  {'LR__C': 0.0039},
  {'LR__C': 0.004},
  {'LR__C': 0.0041},
  {'LR__C': 0.004200000000000001},
  {'LR__C': 0.004300000000000001},
  {'LR__C': 0.0044},
  {'LR__C': 0.0045000000000000005},
  {'LR__C': 0.004600000000000001},
  {'LR__C': 0.0047},
  {'LR__C': 0.0048000000000000004},
  {'LR__C': 0.004900000000000001},
  {'LR__C': 0.005},
  {'LR__C': 0.0051},
  {'LR__C': 0.005200000000000001},
  {'LR__C': 0.005300000000000001},
  {'LR__C': 0.0054},
  {'LR__C': 0.0055000000000000005},
  {'LR__C': 0.005600000000000001},
  {'LR__C': 0.0057},
  {'LR__C': 0.0058000000000000005},
  {'LR__C': 0.005900000000000001},
  {'LR__C': 0.006},
  {'LR__C': 0.0061},
  {'LR__C': 0.006200000000000001},
  {'LR__C': 0.006300000000000001},
  {'LR__C': 0.0064},
  {'LR__C': 0.006500000000000001},
  {'LR__C': 0.006600000000000001},
  {'LR__C': 0.0067},
  {'LR__C': 0.0068000000000000005},
  {'LR__C': 0.006900000000000001},
  {'LR__C': 0.007000000000000001},
  {'LR__C': 0.0071},
  {'LR__C': 0.007200000000000001},
  {'LR__C': 0.007300000000000001},
  {'LR__C': 0.0074},
  {'LR__C': 0.007500000000000001},
  {'LR__C': 0.007600000000000001},
  {'LR__C': 0.0077},
  {'LR__C': 0.0078000000000000005},
  {'LR__C': 0.0079},
  {'LR__C': 0.008},
  {'LR__C': 0.0081},
  {'LR__C': 0.008199999999999999},
  {'LR__C': 0.0083},
  {'LR__C': 0.0084},
  {'LR__C': 0.0085},
  {'LR__C': 0.0086},
  {'LR__C': 0.0087},
  {'LR__C': 0.0088},
  {'LR__C': 0.0089},
  {'LR__C': 0.009},
  {'LR__C': 0.0091},
  {'LR__C': 0.0092},
  {'LR__C': 0.0093},
  {'LR__C': 0.0094},
  {'LR__C': 0.0095},
  {'LR__C': 0.0096},
  {'LR__C': 0.0097},
  {'LR__C': 0.0098},
  {'LR__C': 0.009899999999999999},
  {'LR__C': 0.01}],
 'split0_test_score': array([0.63628, 0.63736, 0.63778, 0.63806, 0.63808, 0.63842, 0.63832,
        0.63836, 0.63824, 0.63814, 0.6383 , 0.63832, 0.63838, 0.63822,
        0.63828, 0.6382 , 0.63828, 0.63816, 0.63816, 0.6381 , 0.63806,
        0.63812, 0.63812, 0.63814, 0.63812, 0.63814, 0.63816, 0.63812,
        0.63814, 0.63812, 0.63808, 0.63808, 0.63808, 0.63802, 0.63806,
        0.63804, 0.638  , 0.63808, 0.63806, 0.6381 , 0.63812, 0.63814,
        0.6381 , 0.63812, 0.63814, 0.63816, 0.6382 , 0.63828, 0.63832,
        0.6383 , 0.63824, 0.63824, 0.63822, 0.63826, 0.63826, 0.6382 ,
        0.63818, 0.6382 , 0.6382 , 0.63818, 0.63804, 0.63806, 0.63806,
        0.63802, 0.63802, 0.63802, 0.63806, 0.6381 , 0.6381 , 0.6381 ,
        0.63808, 0.63802, 0.63802, 0.63802, 0.63802, 0.63804, 0.63804,
        0.63804, 0.63804, 0.63806, 0.63808, 0.63806, 0.63804, 0.63802,
        0.63806, 0.63804, 0.63802, 0.63802, 0.63802, 0.63802, 0.63804,
        0.63802, 0.63798, 0.63796, 0.63794, 0.63794, 0.63794, 0.63794,
        0.63794, 0.63794]),
 'mean_test_score': array([0.63628, 0.63736, 0.63778, 0.63806, 0.63808, 0.63842, 0.63832,
        0.63836, 0.63824, 0.63814, 0.6383 , 0.63832, 0.63838, 0.63822,
        0.63828, 0.6382 , 0.63828, 0.63816, 0.63816, 0.6381 , 0.63806,
        0.63812, 0.63812, 0.63814, 0.63812, 0.63814, 0.63816, 0.63812,
        0.63814, 0.63812, 0.63808, 0.63808, 0.63808, 0.63802, 0.63806,
        0.63804, 0.638  , 0.63808, 0.63806, 0.6381 , 0.63812, 0.63814,
        0.6381 , 0.63812, 0.63814, 0.63816, 0.6382 , 0.63828, 0.63832,
        0.6383 , 0.63824, 0.63824, 0.63822, 0.63826, 0.63826, 0.6382 ,
        0.63818, 0.6382 , 0.6382 , 0.63818, 0.63804, 0.63806, 0.63806,
        0.63802, 0.63802, 0.63802, 0.63806, 0.6381 , 0.6381 , 0.6381 ,
        0.63808, 0.63802, 0.63802, 0.63802, 0.63802, 0.63804, 0.63804,
        0.63804, 0.63804, 0.63806, 0.63808, 0.63806, 0.63804, 0.63802,
        0.63806, 0.63804, 0.63802, 0.63802, 0.63802, 0.63802, 0.63804,
        0.63802, 0.63798, 0.63796, 0.63794, 0.63794, 0.63794, 0.63794,
        0.63794, 0.63794]),
 'std_test_score': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'rank_test_score': array([100,  99,  98,  56,  49,   1,   4,   3,  14,  30,   7,   4,   2,
         17,   9,  19,   9,  26,  26,  43,  56,  36,  36,  30,  36,  30,
         26,  36,  30,  36,  49,  49,  49,  75,  56,  66,  89,  49,  56,
         43,  36,  30,  43,  36,  30,  26,  19,   9,   4,   7,  14,  14,
         17,  12,  12,  19,  24,  19,  19,  24,  66,  56,  56,  75,  75,
         75,  56,  43,  43,  43,  49,  75,  75,  75,  75,  66,  66,  66,
         66,  56,  49,  56,  66,  75,  56,  66,  75,  75,  75,  75,  66,
         75,  90,  91,  92,  92,  92,  92,  92,  92])}